# Dependencies
gems:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-gist

markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Kyle Magee
tagline:          ''
description:      'Software Developer'
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Kyle Magee'
  url:            https://https://kyle-magee.github.io/

paginate:         5

# Custom vars
# version:          2.1.0

github:
  repo:           https://github.com/Kyle-Magee
